#!/usr/bin/env bash
# install nginx web server and create html pages
apt-get -y update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx restart
