#!/usr/bin/env bash
# Install Nginx web server and create HTML pages

# Update package lists
apt-get -y update

# Install Nginx package
apt-get install -y nginx

# Create index.nginx-debian.html file with "Hello World" content
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Add redirection rule for /redirect_me path
cm="rewrite ^/redirect_me https://github.com/mgregchi permanent;"
sudo sed -i "66i $cm" /etc/nginx/sites-available/default

# Create custom_404.html file with "Ceci n'est pas une page" content
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Delete all content in /etc/nginx/sites-available/default
truncate -s 0 /etc/nginx/sites-available/default

# Configure Nginx default site
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html/;
    index  index.html;

    # Redirect /redirect_me path with a 301 status code
    location /redirect_me {
        return 301 https://github.com/mgregchi;
    }

    error_page 404 /custom_404.html;

    location = /custom_404.html {
        root /var/www/html;
        internal;
    }    
}" > /etc/nginx/sites-available/default

# Restart Nginx service
sudo service nginx restart
