#!/usr/bin/env bash
# Install Nginx web server and create HTML pages

# Update package lists
apt-get -y update

# Install Nginx package
apt-get install -y nginx

# Create index.nginx-debian.html file with "Hello World" content
echo "Ceci n'est pas une page" > /var/www/html/index.nginx-debian.html

# Add redirection rule for /redirect_me path
cm="rewrite ^/redirect_me https://github.com/mgregchi permanent;"
sudo sed -i "66i $cm" /etc/nginx/sites-available/default

# Create custom_404.html file with "Ceci n'est pas une page" content
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Add error page configuration for 404 errors
err="\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n"
sudo sed -i "44i $err" /etc/nginx/sites-available/default

# Restart Nginx service
sudo service nginx restart
