#!/usr/bin/env bash
# Install Nginx web server and create HTML pages

# Update package lists
apt-get -y update

# Install Nginx package
apt-get install -y nginx

# Create index.nginx-debian.html file with "Hello World" content
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Add redirection rule for /redirect_me path
cm="rewrite ^/redirect_me https://github.com/mgregchi permanent;"
sudo sed -i "66i $cm" /etc/nginx/sites-available/default

# Create custom_404.html file with "Ceci n'est pas une page" content
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Check if the error page configuration exists
if grep -q "error_page 404 /custom_404.html;" /etc/nginx/sites-available/default; then
    # Replace the existing error page configuration
    sudo sed -i "s/error_page 404 \/custom_404.html;/\\\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default
else
    # Add the error page configuration at the end of file if it doesn't exist
    err="\\\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}\n"
    sudo sed -i "\$a$err" /etc/nginx/sites-available/default
fi

# Restart Nginx service
sudo service nginx restart
