#!/usr/bin/env bash
# create pub file with its own pid and receive SIG
sudo bash -c "echo $$ > /var/run/myscript.pid"
trap "sudo rm -f /var/run/myscript.pid; exit" SIGQUIT
trap "sudo rm -f /var/run/myscript.pid; echo I hate the kill command; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
while :
do
    echo "To infinity and beyond"
    sleep 2
done
