#!/usr/bin/env bash
# loops from 1 to 10 and display multiple strings

i=0
while [ $i -lt 10 ]; do
      (( i+=1 ))
      if [ $i -eq 4 ]
      then
	echo "bad luck"
      elif [ $i -eq 8 ]
      then
	echo "good luck"
      else
	echo "Best School"
      fi
done
