#!/usr/bin/env bash
# displays number from 1 to 20 except...

i=0
while [ $i -lt 20 ]; do
    (( i+=1 ))
    echo "$i"
    case $i in
	4)
	    echo "bad luck from China" ;;
	9)
	    echo "bad luck from Japan" ;;
	17)
	    echo "bad luck from Italy" ;;
	esac
done
